import type { Exercise } from "./types";

export const EXERCISES: Exercise[] = [
  {
    slug: "sentadilla",
    name: "Sentadilla",
    aka: "Squat",
    group: "cuadriceps",
    secondary: ["gluteos", "core"],
    level: "principiante",
    equipment: "peso corporal",
    live: true,
    detector: "squat",
    musclesWorking: ["Cuádriceps", "Glúteos", "Isquiotibiales", "Core"],
    setup: [
      "Coloca el teléfono a 2–3 m, a la altura de la cadera, de frente o en 45°.",
      "Pies al ancho de hombros, puntas ligeramente hacia fuera.",
      "Pecho alto, mirada al frente, peso en el medio del pie.",
    ],
    cues: [
      "Siéntate entre los talones, no hacia delante.",
      "Rodillas siguen la línea de los pies.",
      "Mantén las costillas abajo y el core firme.",
    ],
    commonErrors: [
      {
        error: "Rodillas colapsan hacia dentro",
        fix: "Empuja el suelo hacia fuera y piensa en abrir el suelo con los pies.",
        risk: "Estrés en ligamento colateral y menisco.",
      },
      {
        error: "Talones se levantan",
        fix: "Acorta el descenso o abre un poco más la stance. Peso en el talón y el mediopié.",
        risk: "Sobrecarga de rodilla y pérdida de equilibrio.",
      },
      {
        error: "Tronco se desploma",
        fix: "Saca pecho sin arquear lumbar. Lleva las caderas atrás primero.",
        risk: "Carga excesiva en zona lumbar.",
      },
    ],
    injuryRisks: ["Rodilla", "Lumbar", "Tobillo"],
    met: 5.5,
    summary: "El patrón de sentarse y levantarse. Base de fuerza de piernas y cadera.",
  },
  {
    slug: "sentadilla-sumo",
    name: "Sentadilla sumo",
    group: "gluteos",
    secondary: ["cuadriceps", "isquios"],
    level: "principiante",
    equipment: "peso corporal",
    live: true,
    detector: "squat",
    musclesWorking: ["Glúteos", "Aductores", "Cuádriceps"],
    setup: ["Stance más ancha que hombros.", "Puntas a 30–45°.", "Torso más vertical que en la sentadilla clásica."],
    cues: ["Empuja las rodillas hacia fuera.", "Baja el coxis entre los talones.", "Aprieta glúteos al subir."],
    commonErrors: [
      {
        error: "Rodillas caen hacia dentro",
        fix: "Reduce la anchura hasta controlar las rodillas.",
        risk: "Valgo de rodilla.",
      },
    ],
    injuryRisks: ["Rodilla", "Cadera"],
    met: 5.5,
    summary: "Variante ancha que enfatiza glúteos y aductores.",
  },
  {
    slug: "flexiones",
    name: "Flexiones",
    aka: "Push-up",
    group: "pecho",
    secondary: ["triceps", "hombros", "core"],
    level: "principiante",
    equipment: "peso corporal",
    live: true,
    detector: "pushup",
    musclesWorking: ["Pectoral mayor", "Tríceps", "Deltoides anterior", "Serrato", "Core"],
    setup: [
      "Cámara de lado o a 45° para ver la línea del cuerpo.",
      "Manos bajo los hombros, cuerpo en tabla.",
      "Glúteos y abdomen activos desde el primer segundo.",
    ],
    cues: [
      "Codos a unos 45° del torso, no a 90°.",
      "Pecho al suelo, no solo la cabeza.",
      "Empuja el suelo lejos y termina con omóplatos abiertos.",
    ],
    commonErrors: [
      {
        error: "Cadera cae (lumbar arqueada)",
        fix: "Aprieta glúteos y lleva el pubis hacia las costillas.",
        risk: "Compresión lumbar.",
      },
      {
        error: "Cadera muy alta",
        fix: "Baja la pelvis hasta alinear hombros, cadera y tobillos.",
        risk: "Menos pecho, más hombro anterior.",
      },
      {
        error: "Codos abiertos a 90°",
        fix: "Acerca los codos al torso (~45°).",
        risk: "Impingement de hombro.",
      },
    ],
    injuryRisks: ["Hombro", "Muñeca", "Lumbar"],
    met: 8,
    summary: "Empuje horizontal de peso corporal. Pecho, tríceps y core a la vez.",
  },
  {
    slug: "flexiones-diamante",
    name: "Flexiones diamante",
    group: "triceps",
    secondary: ["pecho", "hombros"],
    level: "intermedio",
    equipment: "peso corporal",
    live: true,
    detector: "pushup",
    musclesWorking: ["Tríceps", "Pectoral interno", "Deltoides anterior"],
    setup: ["Índices y pulgares forman un diamante bajo el pecho.", "Codos rozan el torso al bajar."],
    cues: ["Baja lento.", "No dejes que los hombros se encogan.", "Mantén la tabla."],
    commonErrors: [
      {
        error: "Hombros hacia las orejas",
        fix: "Deprime omóplatos y piensa en alejar el suelo.",
        risk: "Tensión cervical y trapecio.",
      },
    ],
    injuryRisks: ["Codo", "Muñeca"],
    met: 8.5,
    summary: "Flexión cerrada para tríceps. Exige más estabilidad de hombro.",
  },
  {
    slug: "zancadas",
    name: "Zancadas",
    aka: "Lunges",
    group: "cuadriceps",
    secondary: ["gluteos", "isquios"],
    level: "principiante",
    equipment: "peso corporal",
    live: true,
    detector: "lunge",
    musclesWorking: ["Cuádriceps", "Glúteo mayor", "Glúteo medio", "Isquiotibiales"],
    setup: ["Da un paso largo hacia delante.", "Torso erguido.", "Cámara de lado para ver ambas rodillas."],
    cues: [
      "La rodilla delantera sigue el pie, no se mete.",
      "La rodilla trasera baja hacia el suelo con control.",
      "Empuja con el talón delantero para volver.",
    ],
    commonErrors: [
      {
        error: "Rodilla delantera sobrepasa mucho la punta",
        fix: "Alarga el paso. La tibia delantera queda más vertical.",
        risk: "Sobrecarga femoropatelar.",
      },
      {
        error: "Tronco se inclina y la cadera se tuerce",
        fix: "Acorta el paso y aprieta el glúteo de la pierna delantera.",
        risk: "Inestabilidad de cadera y rodilla.",
      },
    ],
    injuryRisks: ["Rodilla", "Cadera"],
    met: 6.5,
    summary: "Patrón unilateral. Corrige desequilibrios entre piernas.",
  },
  {
    slug: "plancha",
    name: "Plancha",
    group: "core",
    secondary: ["hombros", "gluteos"],
    level: "principiante",
    equipment: "peso corporal",
    live: true,
    detector: "plank",
    musclesWorking: ["Transverso", "Recto abdominal", "Oblicuos", "Glúteos", "Hombros"],
    setup: ["Antebrazos o palmas, cuerpo largo.", "Cámara de lado.", "Codos bajo hombros."],
    cues: ["Empuja el suelo.", "Aprieta glúteos.", "Costillas hacia abajo, cuello largo."],
    commonErrors: [
      {
        error: "Cadera cae",
        fix: "Aprieta glúteos y cierra las costillas.",
        risk: "Extensión lumbar dolorosa.",
      },
      {
        error: "Cadera demasiado alta",
        fix: "Baja la pelvis hasta la línea hombro-cadera-tobillo.",
        risk: "Dejas de trabajar el core.",
      },
    ],
    injuryRisks: ["Lumbar", "Hombro", "Muñeca"],
    met: 4,
    summary: "Isométrico de core. Calidad de línea, no récord de tiempo.",
  },
  {
    slug: "curl-biceps",
    name: "Curl de bíceps",
    group: "biceps",
    secondary: ["hombros"],
    level: "principiante",
    equipment: "mancuernas",
    live: true,
    detector: "curl",
    musclesWorking: ["Bíceps braquial", "Braquial", "Braquiorradial"],
    setup: ["De pie, codos pegados al torso.", "Cámara de frente o 45°.", "Muñecas neutras."],
    cues: ["El codo no viaja hacia delante.", "Sube en 1 s, baja en 2–3 s.", "No balancees la cadera."],
    commonErrors: [
      {
        error: "Balanceo de tronco",
        fix: "Reduce el peso. Aprieta glúteos y costillas.",
        risk: "Lumbar y hombro anterior.",
      },
      {
        error: "Codos se adelantan",
        fix: "Imagina que los codos están clavados en las costillas.",
        risk: "Menos bíceps, más deltoides.",
      },
    ],
    injuryRisks: ["Codo", "Muñeca"],
    met: 3.5,
    summary: "Aislamiento de bíceps. El control en la bajada es el trabajo real.",
  },
  {
    slug: "press-militar",
    name: "Press militar",
    aka: "Overhead press",
    group: "hombros",
    secondary: ["triceps", "core"],
    level: "intermedio",
    equipment: "mancuernas",
    live: true,
    detector: "press",
    musclesWorking: ["Deltoides", "Tríceps", "Trapecio superior", "Core"],
    setup: ["De pie, costillas abajo.", "Empuja vertical, no hacia delante.", "Cámara de frente."],
    cues: ["Glúteos y abdomen firmes.", "Cabeza pasa ligeramente al final.", "No arquees la lumbar."],
    commonErrors: [
      {
        error: "Lumbar se arquea para terminar el press",
        fix: "Baja el peso. Aprieta glúteos y costillas. Recorta el rango si hace falta.",
        risk: "Compresión lumbar y pinzamiento de hombro.",
      },
    ],
    injuryRisks: ["Hombro", "Lumbar"],
    met: 4.5,
    summary: "Empuje vertical. Exige hombro sano y core que no deje arching.",
  },
  {
    slug: "peso-muerto",
    name: "Peso muerto rumano",
    aka: "RDL / hip hinge",
    group: "isquios",
    secondary: ["gluteos", "espalda"],
    level: "intermedio",
    equipment: "mancuernas",
    live: true,
    detector: "hinge",
    musclesWorking: ["Isquiotibiales", "Glúteos", "Erectores", "Dorsales"],
    setup: ["Pies al ancho de cadera.", "Empuja las caderas atrás, rodillas suaves.", "Cámara de lado."],
    cues: ["La barra o mancuernas rozan el muslo.", "Espalda larga, no redonda.", "Vuelve apretando glúteos, no la lumbar."],
    commonErrors: [
      {
        error: "La lumbar se redondea",
        fix: "Acorta el rango. Saca pecho y empuja más la cadera atrás.",
        risk: "Hernia / distensión lumbar.",
      },
      {
        error: "Se convierte en sentadilla (rodillas se doblan demasiado)",
        fix: "Piensa en cerrar un cajón con los glúteos. Tibia casi vertical.",
        risk: "Pierdes el estímulo de isquios.",
      },
    ],
    injuryRisks: ["Lumbar", "Isquiotibiales"],
    met: 6,
    summary: "Bisagra de cadera. El patrón más importante para la cadena posterior.",
  },
  {
    slug: "fondos",
    name: "Fondos de tríceps",
    group: "triceps",
    secondary: ["pecho", "hombros"],
    level: "intermedio",
    equipment: "banco",
    live: true,
    detector: "generic",
    musclesWorking: ["Tríceps", "Pectoral inferior", "Deltoides anterior"],
    setup: ["Manos en un banco, dedos al frente.", "Cadera cerca del banco.", "Hombros lejos de las orejas."],
    cues: ["Baja hasta ~90° de codo.", "No dejes que los hombros se hundan.", "Empuja el banco hacia abajo."],
    commonErrors: [
      {
        error: "Hombros se hunden por debajo de los codos",
        fix: "Reduce el rango. Mantén el pecho abierto y los omóplatos bajos.",
        risk: "Inestabilidad glenohumeral.",
      },
    ],
    injuryRisks: ["Hombro", "Muñeca"],
    met: 5,
    summary: "Extensión de codo con el tronco vertical. Cuidado con el hombro anterior.",
  },
  {
    slug: "crunch",
    name: "Crunch",
    group: "core",
    secondary: [],
    level: "principiante",
    equipment: "peso corporal",
    live: true,
    detector: "crunch",
    musclesWorking: ["Recto abdominal", "Oblicuos"],
    setup: ["Boca arriba, rodillas flexionadas.", "Manos en sienes, no en nuca.", "Cámara de lado."],
    cues: ["Enrolla el pecho hacia las caderas.", "Lumbar sigue en el suelo.", "Baja vertebra a vertebra."],
    commonErrors: [
      {
        error: "Tiras del cuello",
        fix: "Mantén un puño de espacio entre mentón y pecho. Empuja la lengua al paladar.",
        risk: "Cervicalgia.",
      },
    ],
    injuryRisks: ["Cuello", "Lumbar"],
    met: 3.5,
    summary: "Flexión torácica corta. No es un sit-up completo.",
  },
  {
    slug: "jumping-jacks",
    name: "Jumping jacks",
    group: "cardio",
    secondary: ["cuerpo"],
    level: "principiante",
    equipment: "peso corporal",
    live: true,
    detector: "jacks",
    musclesWorking: ["Gemelos", "Hombros", "Aductores", "Core"],
    setup: ["Espacio libre alrededor.", "Aterriza suave, rodillas elásticas."],
    cues: ["Brazos y piernas a la vez.", "Aterriza de mediopié.", "Mantén el abdomen firme."],
    commonErrors: [
      {
        error: "Aterrizaje rígido de talón",
        fix: ["Rodillas blandas", "piensa en el suelo como un trampolín"].join(". "),
        risk: "Rodilla y lumbar.",
      },
    ],
    injuryRisks: ["Rodilla", "Tobillo"],
    met: 8,
    summary: "Calentamiento y cardio de bajo material.",
  },
  {
    slug: "mountain-climbers",
    name: "Mountain climbers",
    group: "cardio",
    secondary: ["core", "hombros"],
    level: "intermedio",
    equipment: "peso corporal",
    live: true,
    detector: "climber",
    musclesWorking: ["Core", "Psoas", "Hombros", "Cuádriceps"],
    setup: ["Posición de plancha alta.", "Cadera estable, no un sube-baja."],
    cues: ["Lleva la rodilla hacia el pecho, no hacia un lado.", "Manos empujan el suelo.", "Respira en ritmo."],
    commonErrors: [
      {
        error: "Cadera rebota",
        fix: "Reduce la velocidad. Piensa en una plancha que camina.",
        risk: "Lumbar y muñecas.",
      },
    ],
    injuryRisks: ["Muñeca", "Hombro", "Lumbar"],
    met: 8.5,
    summary: "Cardio en plancha. El core no debe colapsar al acelerar.",
  },
  {
    slug: "elevacion-gemelos",
    name: "Elevación de gemelos",
    group: "gemelos",
    secondary: [],
    level: "principiante",
    equipment: "peso corporal",
    live: true,
    detector: "calfraise",
    musclesWorking: ["Gastrocnemio", "Sóleo"],
    setup: ["Pies al ancho de cadera.", "Opcional: antepié en un escalón para más rango."],
    cues: ["Sube al máximo, pausa 1 s.", "Baja lento hasta estirar.", "No rebotes."],
    commonErrors: [
      {
        error: "Rebote en la parte baja",
        fix: "Pausa arriba y abajo. Rango completo y controlado.",
        risk: "Tendón de Aquiles.",
      },
    ],
    injuryRisks: ["Aquiles", "Tobillo"],
    met: 3,
    summary: "Fuerza de pantorrilla. Clave para saltar y aterrizar bien.",
  },
  {
    slug: "burpees",
    name: "Burpees",
    group: "cuerpo",
    secondary: ["cardio", "pecho"],
    level: "avanzado",
    equipment: "peso corporal",
    live: true,
    detector: "burpee",
    musclesWorking: ["Cuerpo completo", "Pecho", "Cuádriceps", "Core"],
    setup: ["Espacio para tumbarte y saltar.", "Versión sin salto si hay molestia de rodilla."],
    cues: ["Manos al suelo, pies atrás, flexión opcional, pies delante, salto.", "No dejes caer la lumbar en el suelo."],
    commonErrors: [
      {
        error: "Colapso lumbar al ir al suelo",
        fix: "Baja con control. Flexión de rodillas y cadera, no un golpe.",
        risk: "Lumbar y muñecas.",
      },
    ],
    injuryRisks: ["Muñeca", "Hombro", "Rodilla", "Lumbar"],
    met: 10,
    summary: "Condicionamiento total. La técnica importa más que la velocidad.",
  },
  {
    slug: "wall-sit",
    name: "Wall sit",
    group: "cuadriceps",
    secondary: ["gluteos"],
    level: "principiante",
    equipment: "peso corporal",
    live: true,
    detector: "wallsit",
    musclesWorking: ["Cuádriceps", "Glúteos", "Core"],
    setup: ["Espalda plana contra la pared.", "Rodillas a ~90°.", "Pies al ancho de cadera."],
    cues: ["Peso en talones.", "No empujes con las manos en los muslos.", "Respira; no aguantes la respiración."],
    commonErrors: [
      {
        error: "Rodillas por delante de los pies y talones levantados",
        fix: "Avanza un poco los pies. Baja hasta que los muslos queden paralelos.",
        risk: "Dolor anterior de rodilla.",
      },
    ],
    injuryRisks: ["Rodilla"],
    met: 4,
    summary: "Isométrico de cuádriceps. Ideal para acumular tiempo bajo tensión.",
  },
  {
    slug: "hip-thrust",
    name: "Hip thrust",
    group: "gluteos",
    secondary: ["isquios", "core"],
    level: "principiante",
    equipment: "peso corporal",
    live: true,
    detector: "hipthrust",
    musclesWorking: ["Glúteo mayor", "Isquiotibiales", "Core"],
    setup: ["Omóplatos sobre un banco o en el suelo (puente).", "Mentón metido, costillas abajo."],
    cues: ["Empuja el pubis al techo.", "Aprieta 1 s arriba sin hiperextender lumbar.", "Baja con control."],
    commonErrors: [
      {
        error: "Arqueas la lumbar en vez de extender la cadera",
        fix: "Costillas abajo. Piensa en meter el coxis, no en mirar al techo.",
        risk: "Extensión lumbar excesiva.",
      },
    ],
    injuryRisks: ["Lumbar"],
    met: 4.5,
    summary: "El mejor patrón para glúteo mayor si la lumbar se queda neutra.",
  },
  {
    slug: "dominadas",
    name: "Dominadas",
    aka: "Pull-up",
    group: "espalda",
    secondary: ["biceps", "hombros"],
    level: "avanzado",
    equipment: "peso corporal",
    live: false,
    detector: "generic",
    musclesWorking: ["Dorsal ancho", "Bíceps", "Romboides", "Core"],
    setup: ["Agarre prono al ancho de hombros.", "Escápulas abajo y atrás antes de tirar."],
    cues: ["Pecho a la barra.", "No encogas trapecios.", "Baja hasta brazos largos con control."],
    commonErrors: [
      {
        error: "Balanceo y cuello por encima de la barra",
        fix: "Kipping solo si es el objetivo. Para fuerza: cuerpo tenso, mentón por encima sin encoger.",
        risk: "Hombro y codo.",
      },
    ],
    injuryRisks: ["Hombro", "Codo"],
    met: 8,
    summary: "El rey del jalón vertical. Progresa con australianas o banda si no hay repetición estricta.",
  },
  {
    slug: "remo-invertido",
    name: "Remo invertido",
    group: "espalda",
    secondary: ["biceps", "core"],
    level: "principiante",
    equipment: "peso corporal",
    live: false,
    detector: "generic",
    musclesWorking: ["Dorsales", "Romboides", "Bíceps", "Core"],
    setup: ["Barra a media altura o mesa estable.", "Cuerpo en tabla, talones al suelo."],
    cues: ["Tira de los codos a las caderas.", "Aprieta omóplatos al final.", "No dejes caer la cadera."],
    commonErrors: [
      {
        error: "Cadera cae y tiras solo de brazos",
        fix: "Aprieta glúteos. Piensa en un press invertido de todo el cuerpo.",
        risk: "Hombro anterior.",
      },
    ],
    injuryRisks: ["Hombro"],
    met: 5.5,
    summary: "Jalón horizontal accesible. Puente hacia las dominadas.",
  },
  {
    slug: "pike-push-up",
    name: "Pike push-up",
    group: "hombros",
    secondary: ["triceps", "core"],
    level: "intermedio",
    equipment: "peso corporal",
    live: true,
    detector: "pushup",
    musclesWorking: ["Deltoides", "Tríceps", "Trapecio superior"],
    setup: ["Cadera alta, cabeza entre los brazos.", "Manos al ancho de hombros."],
    cues: ["Codos a 45°.", "Cabeza hacia el suelo entre las manos.", "Empuja el suelo lejos."],
    commonErrors: [
      {
        error: "Se convierte en flexión normal",
        fix: "Sube más la cadera. Camina los pies hacia las manos.",
        risk: "Menos hombro, más pecho.",
      },
    ],
    injuryRisks: ["Hombro", "Muñeca"],
    met: 7,
    summary: "Progresión a pino. Empuje vertical con peso corporal.",
  },
  {
    slug: "bird-dog",
    name: "Bird dog",
    group: "core",
    secondary: ["gluteos", "espalda"],
    level: "principiante",
    equipment: "peso corporal",
    live: false,
    detector: "generic",
    musclesWorking: ["Multífidos", "Glúteo", "Hombro", "Core"],
    setup: ["Cuadrupedia, muñecas bajo hombros, rodillas bajo cadera."],
    cues: ["Brazo y pierna contrarios largos.", "Cadera cuadrada, sin rotar.", "Pausa 2 s."],
    commonErrors: [
      {
        error: "La lumbar se hunde y la cadera se abre",
        fix: "Reduce el rango. Imagina un vaso de agua en la lumbar.",
        risk: "Extensión lumbar.",
      },
    ],
    injuryRisks: ["Lumbar"],
    met: 2.5,
    summary: "Estabilidad anti-rotación. Oro para espalda sana.",
  },
  {
    slug: "dead-bug",
    name: "Dead bug",
    group: "core",
    secondary: [],
    level: "principiante",
    equipment: "peso corporal",
    live: false,
    detector: "generic",
    musclesWorking: ["Transverso", "Recto abdominal", "Oblicuos"],
    setup: ["Boca arriba, brazos al techo, rodillas a 90°.", "Lumbar pegada al suelo."],
    cues: ["Extiende brazo y pierna contrarios sin despegar la lumbar.", "Exhala al alejar."],
    commonErrors: [
      {
        error: "La lumbar se archa al estirar la pierna",
        fix: "Acorta el rango. Exhala fuerte y empuja el ombligo al suelo.",
        risk: "Extensión lumbar.",
      },
    ],
    injuryRisks: ["Lumbar"],
    met: 2.5,
    summary: "Core en supino. Enseña a no arching cuando las piernas se mueven.",
  },
  {
    slug: "sentadilla-bulgara",
    name: "Sentadilla búlgara",
    group: "cuadriceps",
    secondary: ["gluteos"],
    level: "intermedio",
    equipment: "banco",
    live: true,
    detector: "lunge",
    musclesWorking: ["Cuádriceps", "Glúteos", "Aductores"],
    setup: ["Pie trasero en un banco bajo.", "Torso ligero hacia delante.", "Cámara de lado."],
    cues: ["La rodilla delantera sigue el pie.", "Baja la cadera, no solo la rodilla.", "Empuja el suelo."],
    commonErrors: [
      {
        error: "Demasiado peso en el pie de atrás",
        fix: "Acerca el banco. El 80–90% del peso va delante.",
        risk: "Flexor de cadera y rodilla trasera.",
      },
    ],
    injuryRisks: ["Rodilla", "Cadera"],
    met: 6.5,
    summary: "Unilateral exigente. Construye piernas y equilibrio.",
  },
  {
    slug: "face-pull",
    name: "Face pull",
    group: "hombros",
    secondary: ["espalda"],
    level: "principiante",
    equipment: "banda",
    live: false,
    detector: "generic",
    musclesWorking: ["Deltoides posterior", "Romboides", "Manguito rotador"],
    setup: ["Banda a la altura de la cara.", "Tira hacia la cara abriendo las manos."],
    cues: ["Codos altos.", "Rota las manos hacia atrás al final.", "No encogas trapecio."],
    commonErrors: [
      {
        error: "Tiras hacia el pecho como un remo",
        fix: "Apunta a la cara. Piensa en un bigote de manillar.",
        risk: "Pierdes el trabajo de deltoides posterior.",
      },
    ],
    injuryRisks: ["Hombro"],
    met: 3,
    summary: "Salud de hombro. El antídoto a tanto empuje.",
  },
  {
    slug: "remo-mancuerna",
    name: "Remo con mancuerna",
    group: "espalda",
    secondary: ["biceps"],
    level: "principiante",
    equipment: "mancuernas",
    live: false,
    detector: "generic",
    musclesWorking: ["Dorsal", "Romboides", "Bíceps", "Erectores"],
    setup: ["Una mano y rodilla en banco, espalda plana.", "La mancuerna cuelga bajo el hombro."],
    cues: ["Codo al culo, no al techo.", "Pausa 1 s arriba.", "No gires el tronco."],
    commonErrors: [
      {
        error: "Rotas el tronco para subir más peso",
        fix: "Baja el peso. El omóplato se junta, el pecho no se abre hacia el techo.",
        risk: "Lumbar.",
      },
    ],
    injuryRisks: ["Lumbar", "Hombro"],
    met: 4.5,
    summary: "Jalón unilateral. Fácil de cargar y de sentir el dorsal.",
  },
  {
    slug: "press-banca",
    name: "Press banca",
    group: "pecho",
    secondary: ["triceps", "hombros"],
    level: "intermedio",
    equipment: "barra",
    live: false,
    detector: "generic",
    musclesWorking: ["Pectoral", "Tríceps", "Deltoides anterior"],
    setup: ["Omóplatos juntos y abajo.", "Pies firmes.", "Barra sobre el pecho inferior."],
    cues: ["Baja con control a la línea del pezón.", "Antebrazo vertical.", "No rebotes en el pecho."],
    commonErrors: [
      {
        error: "Muñecas quebradas y codos a 90°",
        fix: "Nudillos al techo. Codos ~45–70°.",
        risk: "Hombro y muñeca.",
      },
    ],
    injuryRisks: ["Hombro", "Muñeca", "Pectoral"],
    met: 5,
    summary: "Empuje horizontal cargado. Respeta el omóplato retraído.",
  },
  {
    slug: "plancha-lateral",
    name: "Plancha lateral",
    group: "core",
    secondary: ["hombros"],
    level: "intermedio",
    equipment: "peso corporal",
    live: true,
    detector: "plank",
    musclesWorking: ["Oblicuos", "Glúteo medio", "Hombro"],
    setup: ["Antebrazo bajo el hombro.", "Cadera arriba, cuerpo en línea.", "Cámara de frente."],
    cues: ["Empuja el suelo.", "Cadera ni cae ni se adelanta.", "Cuello largo."],
    commonErrors: [
      {
        error: "Cadera rota hacia delante y se hunde",
        fix: ["Aprieta glúteo", "empuja la cadera al techo"].join(", "),
        risk: "Hombro de apoyo.",
      },
    ],
    injuryRisks: ["Hombro", "Lumbar"],
    met: 4,
    summary: "Anti-flexión lateral. Glúteo medio y oblicuos a la vez.",
  },
  {
    slug: "swing-mancuerna",
    name: "Swing con mancuerna",
    group: "gluteos",
    secondary: ["isquios", "core", "cardio"],
    level: "intermedio",
    equipment: "mancuernas",
    live: true,
    detector: "hinge",
    musclesWorking: ["Glúteos", "Isquiotibiales", "Core", "Hombros"],
    setup: ["Mancuerna a dos manos.", "Bisagra explosiva, no sentadilla."],
    cues: ["La cadera lanza, los brazos solo guían.", "Arriba a la altura del pecho.", "Costillas abajo."],
    commonErrors: [
      {
        error: "Elevas con los hombros y arqueas lumbar",
        fix: "El peso flota por el empujón de cadera. Termina apretando glúteos, no mirando al techo.",
        risk: "Lumbar.",
      },
    ],
    injuryRisks: ["Lumbar", "Hombro"],
    met: 9,
    summary: "Potencia de cadera. Cardio de fuerza si el hinge es limpio.",
  },
  {
    slug: "step-up",
    name: "Step-up",
    group: "cuadriceps",
    secondary: ["gluteos"],
    level: "principiante",
    equipment: "banco",
    live: true,
    detector: "generic",
    musclesWorking: ["Cuádriceps", "Glúteos", "Gemelos"],
    setup: ["Banco estable a altura de rodilla o menos.", "Todo el pie en la superficie."],
    cues: ["Empuja con la pierna de arriba.", "La de abajo no hace trampa rebotando.", "Cadera alta al terminar."],
    commonErrors: [
      {
        error: "Impulso con la pierna de abajo",
        fix: "Pausa 1 s arriba. Baja en 3 s.",
        risk: "Rodilla de la pierna de trabajo.",
      },
    ],
    injuryRisks: ["Rodilla"],
    met: 6,
    summary: "Unilateral funcional. Subir un cajón con control es fuerza real.",
  },
  {
    slug: "extension-triceps",
    name: "Extensión de tríceps",
    group: "triceps",
    secondary: ["hombros"],
    level: "principiante",
    equipment: "mancuernas",
    live: true,
    detector: "generic",
    musclesWorking: ["Tríceps (cabeza larga)"],
    setup: ["Mancuerna a dos manos sobre la cabeza, o una por brazo.", "Codos a las orejas."],
    cues: ["Solo se mueve el antebrazo.", "No dejes que los codos se abran.", "Baja hasta estirar."],
    commonErrors: [
      {
        error: "Codos se abren y lumbar se arquea",
        fix: "Aprieta glúteos. Reduce el peso. Codos mirando al frente.",
        risk: "Codo y lumbar.",
      },
    ],
    injuryRisks: ["Codo", "Hombro"],
    met: 3.5,
    summary: "Aislamiento de tríceps en largo. El codo estable es el ejercicio.",
  },
  {
    slug: "elevaciones-laterales",
    name: "Elevaciones laterales",
    group: "hombros",
    secondary: [],
    level: "principiante",
    equipment: "mancuernas",
    live: true,
    detector: "generic",
    musclesWorking: ["Deltoides medio"],
    setup: ["Codos suaves, mancuernas a los lados.", "Tronco quieto."],
    cues: ["Eleva hasta un poco por debajo del hombro.", "Meñique ligeramente arriba.", "Baja en 2–3 s."],
    commonErrors: [
      {
        error: "Balanceo y encogimiento de trapecio",
        fix: "Peso ridículamente ligero. Piensa en verter una jarra, no en encoger." ,
        risk: "Trapecio y manguito.",
      },
    ],
    injuryRisks: ["Hombro"],
    met: 3.5,
    summary: "El deltoides medio se entrena con ego bajo y control alto.",
  },
  {
    slug: "puente-gluteo",
    name: "Puente de glúteos",
    group: "gluteos",
    secondary: ["isquios", "core"],
    level: "principiante",
    equipment: "peso corporal",
    live: true,
    detector: "hipthrust",
    musclesWorking: ["Glúteo mayor", "Isquiotibiales"],
    setup: ["Boca arriba, pies cerca de los glúteos.", "Brazos a los lados."],
    cues: ["Empuja talones.", "Pausa arriba.", "No hiperextiendas."],
    commonErrors: [
      {
        error: "Empujas con la lumbar",
        fix: "Costillas abajo. El movimiento nace de la cadera.",
        risk: "Lumbar.",
      },
    ],
    injuryRisks: ["Lumbar"],
    met: 3.5,
    summary: "Versión en suelo del hip thrust. Perfecta para aprender el apretón.",
  },
  {
    slug: "isometrico-core-hollow",
    name: "Hollow body hold",
    group: "core",
    secondary: [],
    level: "intermedio",
    equipment: "peso corporal",
    live: false,
    detector: "generic",
    musclesWorking: ["Recto abdominal", "Transverso", "Flexores de cadera"],
    setup: ["Boca arriba, lumbar pegada.", "Brazos y piernas largos a unos 30°."],
    cues: ["Exhala y pega la lumbar.", "Si se despega, dobla rodillas."],
    commonErrors: [
      {
        error: "Lumbar en arco y respiración contenida",
        fix: "Regresa a tuck hollow. La lumbar no negocia.",
        risk: "Psoas y lumbar.",
      },
    ],
    injuryRisks: ["Lumbar"],
    met: 3.5,
    summary: "La forma de gimnasia del core. Base de pino y dominadas estrictas.",
  },
];

const bySlug = new Map(EXERCISES.map((e) => [e.slug, e]));

export function getExercise(slug: string): Exercise | undefined {
  return bySlug.get(slug);
}
